version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: timetrack_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: timetrack
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata: null